# Generated by Django 5.2.2 on 2025-07-30 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_add_trip_type_and_checklist'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_index', models.IntegerField()),
                ('place_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('user_ratings_total', models.IntegerField(blank=True, null=True)),
                ('types', models.JSONField(blank=True, default=list)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('user_notes', models.TextField(blank=True)),
                ('is_visited', models.BooleanField(default=False)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('user_rating', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to='trips.trip')),
            ],
            options={
                'ordering': ['stop_index', 'name'],
                'unique_together': {('trip', 'place_id')},
            },
        ),
    ]
